* QU TAD LaTeX Template
  This is an attempt to clone [[http://www.qu.edu.qa/research/graduate-studies/current-students/TAD-Services][Qatar University's TAD engineering template]] to LaTeX. Note that it is not official yet.

** Is this usable?
   Some students confirmed submitting using this template for Spring 2020. So, probably yes. If anything is wrong TAD would reply specifying their comments. If they do and you don't know how to fix it, start an issue here.

** Usage
   ~thesis.tex~ should contain you actual work and ~refs.bib~ is your bibliography file.

   Compile with ~xelatex~ and ~biber~.

   ~thesis-org.org~ can be also used if you are an Emacs org-mode user. You would also need to evaluate ~qutad.el~ to add the LaTeX class. You can also add its content to your Emacs init file if you like.

** Contribution
   Pull requests are welcomed. If any difference from the original Word template was found please report an issue. Also, help on the known issues bellow is needed.

** Known issues
   No known issues so far. If you find any, start an issue here.

** License
   [[https://www.latex-project.org/lppl.txt][LPPL]]
